const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2018-2022",
    title: "Bachelor's Degree",
    desc: "Faculty of Computers and Artificial Intelligence, Banha University.",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2022-2023",
    title: "Intensive Scholarship",
    desc: "ITI",
  },
  {
    id: 3,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022-2023",
    title: "Frontend and Cross Platform Mob Dev",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
  },
  {
    id: 4,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022-2023",
    title: "Professional Web Development",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022-2023",
    title: "Frontend and Cross Platform Mob Dev",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022-2023",
    title: "Professional Web Development",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
  },
  {
    id: 7,
    category: "education",
    icon: "icon-graduation",
    year: "2018-2022",
    title: "Bachelor's Degree",
    desc: "Faculty of Computers and Artificial Intelligence, Banha University.",
  },
  {
    id: 8,
    category: "education",
    icon: "icon-graduation",
    year: "2022-2023",
    title: "Intensive Scholarship",
    desc: "ITI",
  },
];

export default Data;
